const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/inventoryController');
const { authenticate, authorize, requirePermission } = require('../middleware/auth');
router.use(authenticate);
router.get('/', requirePermission('inventory', 'view'), ctrl.getInventory);
router.get('/transactions', requirePermission('inventory', 'view'), ctrl.getTransactions);
router.post('/stock-in', authorize('super_admin', 'admin', 'manager', 'inventory_user'), requirePermission('inventory', 'create'), ctrl.stockIn);
router.post('/stock-out', authorize('super_admin', 'admin', 'manager', 'inventory_user'), requirePermission('inventory', 'create'), ctrl.stockOut);
router.post('/adjustment', authorize('super_admin', 'admin', 'manager'), requirePermission('inventory', 'edit'), ctrl.adjustment);
router.post('/transfer', authorize('super_admin', 'admin', 'manager'), requirePermission('inventory', 'edit'), ctrl.transfer);
module.exports = router;
