const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/notificationController');
const { authenticate, requirePermission } = require('../middleware/auth');
router.use(authenticate);
router.get('/', requirePermission('notifications', 'view'), ctrl.getAll);
router.post('/check-stock', requirePermission('notifications', 'create'), ctrl.checkLowStock);
router.patch('/mark-all-read', requirePermission('notifications', 'edit'), ctrl.markAllRead);
router.patch('/:id/read', requirePermission('notifications', 'edit'), ctrl.markRead);
module.exports = router;
