const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/purchaseController');
const { authenticate, authorize, requirePermission } = require('../middleware/auth');
router.use(authenticate);
router.get('/', requirePermission('purchases', 'view'), ctrl.getAll);
router.get('/:id/pdf', requirePermission('purchases', 'view'), ctrl.generatePDF);
router.get('/:id', requirePermission('purchases', 'view'), ctrl.getById);
router.post('/', authorize('super_admin', 'admin', 'manager'), requirePermission('purchases', 'create'), ctrl.create);
router.patch('/:id/status', authorize('super_admin', 'admin', 'manager'), requirePermission('purchases', 'edit'), ctrl.updateStatus);
router.delete('/:id', authorize('super_admin', 'admin'), requirePermission('purchases', 'delete'), ctrl.remove);
module.exports = router;
