const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/reportController');
const { authenticate, authorize, requirePermission } = require('../middleware/auth');
router.use(authenticate, authorize('super_admin', 'admin', 'manager'));
router.get('/inventory', requirePermission('reports', 'view'), ctrl.getInventoryReport);
router.get('/purchases', requirePermission('reports', 'view'), ctrl.getPurchaseReport);
router.get('/sales', requirePermission('reports', 'view'), ctrl.getSalesReport);
router.get('/profit-loss', requirePermission('reports', 'view'), ctrl.getProfitLossReport);
module.exports = router;
