const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/warehouseController');
const { authenticate, authorize, requirePermission } = require('../middleware/auth');
router.use(authenticate);
router.get('/', requirePermission('warehouses', 'view'), ctrl.getAll);
router.get('/:id/inventory', requirePermission('warehouses', 'view'), ctrl.getInventory);
router.get('/:id', requirePermission('warehouses', 'view'), ctrl.getById);
router.post('/', authorize('super_admin', 'admin'), requirePermission('warehouses', 'create'), ctrl.create);
router.put('/:id', authorize('super_admin', 'admin'), requirePermission('warehouses', 'edit'), ctrl.update);
router.delete('/:id', authorize('super_admin'), requirePermission('warehouses', 'delete'), ctrl.remove);
module.exports = router;
